pipeline {
    agent any
    
    environment {
        JAVA_HOME = tool name: 'JDK 17', type: 'Tool'  // Ensure JDK 23 is configured in Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/popcorn1297/test_java.git'
            }
        }

        stage('Compile') {
            steps {
                script {
                    echo 'Compiling the Java application...'
                    sh "${JAVA_HOME}/bin/javac Calculator.java"  // Adjust path if necessary
                }
            }
        }

        stage('Run') {
            steps {
                script {
                    echo 'Running the Java application...'
                    sh "${JAVA_HOME}/bin/java Calculator"  // Run the Calculator class
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished.'
        }

        success {
            echo 'Build succeeded!'
        }

        failure {
            echo 'Build failed.'
        }
    }
}

